@ReminderTask_HostAddress = https://localhost:7058

GET {{ReminderTask_HostAddress}}/api/reminders/
Accept: application/json

###

GET {{ReminderTask_HostAddress}}/api/reminders/f84aafb1-686c-4546-8aa2-5d36e52a001c
Accept: application/json

###

POST {{ReminderTask_HostAddress}}/api/reminders
Content-Type: application/json

{
  "message": "Test with mail",
  "sendAt": "2026-01-13T14:10:00",
  "email": "dzejlan.sabic96@gmail.com"
}

###

POST {{ReminderTask_HostAddress}}/api/reminders
Content-Type: application/json

{
  "message": "Test without email",
  "sendAt": "2026-01-13T14:12:00",
  "email": null
}

###

DELETE {{ReminderTask_HostAddress}}/api/reminders/33ac3506-d4df-4e0d-bdde-ca0d6a7535f8
Accept: application/json

###

PUT {{ReminderTask_HostAddress}}/api/reminders/f84aafb1-686c-4546-8aa2-5d36e52a001c
Content-Type: application/json

{
  "id": "f84aafb1-686c-4546-8aa2-5d36e52a001c",
  "message": "Updated with utc",
  "sendAt": "2026-01-13T13:01:00",
  "email": "dzejlan.sabic96@gmail.com"
}

###
