@ReminderTask_HostAddress = https://localhost:7058

GET {{ReminderTask_HostAddress}}/api/reminders/
Accept: application/json

###

GET {{ReminderTask_HostAddress}}/api/reminders/f84aafb1-686c-4546-8aa2-5d36e52a001c
Accept: application/json

###

POST {{ReminderTask_HostAddress}}/api/reminders
Content-Type: application/json

{
  "message": "Test service layer",
  "sendAt": "2026-01-13T15:14:00",
  "email": "dzejlan.sabic96@gmail.com"
}

###

POST {{ReminderTask_HostAddress}}/api/reminders
Content-Type: application/json

{
  "message": "Test without email",
  "sendAt": "2026-01-13T14:12:00",
  "email": null
}

###

DELETE {{ReminderTask_HostAddress}}/api/reminders/f9093fec-1531-4b4f-827b-2437a10206ef
Accept: application/json

###

PUT {{ReminderTask_HostAddress}}/api/reminders/49a7a3d7-01db-4221-9aa7-1c7d2cb84a97
Content-Type: application/json

{
  "id": "49a7a3d7-01db-4221-9aa7-1c7d2cb84a97",
  "message": "Updated with utc upd",
  "sendAt": "2026-01-18T13:01:00",
  "email": "dzejlan.sabic96@gmail.com"
}

###
